### ISSUE TITLE
Mac OS X Installation failed

### ISSUE THREAD

**Issue by ueberf** [snipsco/hermes-protocol#119]
# What is the issue
I want to install hermes on my Mac and followed the instructions as stated [here](https://www.npmjs.com/package/hermes-javascript), but the installation fails with 53 warnings and 5 errors. Building from the sources leads to the same results.

I'm just getting started with snips and hermes and am quite lost on how to fix this problem. Any suggestions?

<img width="892" alt="Screenshot 2019-05-26 at 15 54 32" src="https://user-images.githubusercontent.com/19748898/58382762-9289b680-7fce-11e9-9322-24979befd392.png">

# Logs
[2019-05-26T13_49_20_998Z-debug.log](https://github.com/snipsco/hermes-protocol/files/3220372/2019-05-26T13_49_20_998Z-debug.log)

**Comment by elbywan** [comment]
Hi @ueberf, thanks for reporting your issue!

I see from the logs that you are using node v12 (`node@v12.3.1`).
`hermes-javascript` depends on the `ref` library which does not seem to be compatible with node 12 (see [there](https://github.com/TooTallNate/ref/issues/107)).

Could you try with node v10 LTS instead ?

**Comment by ueberf** [comment]
Fantastic, downgrading to node v10 did the trick! 
Thanks ✌
