### ISSUE TITLE
[Python][Packages] Please provide binary wheel for python 3.7 on arm for Raspbian Buster

### ISSUE THREAD

**Issue by flyser** [snipsco/hermes-protocol#133]
Raspbian recently upgraded to debian buster and therefore comes with python 3.7. Please provide precompiled wheels for hermes-python for this version on pypi.

**Comment by anthonyray** [comment]
Sure, I will look into it !

**Comment by anthonyray** [comment]
Done ! You should have pre-compiled wheels ready for Python3.7 under `armv7` and `armv6` now and in the next builds.
