### ISSUE TITLE
Can't install hermes-javascript

### ISSUE THREAD

**Issue by jakemonton** [snipsco/hermes-protocol#166]
Hi, I can't install the hermes-javascript npm module. Please see attached.

Node version: v12.10.0
NPM version: 6.11.3

<img width="1136" alt="Screen Shot 2019-10-10 at 2 01 29 pm" src="https://user-images.githubusercontent.com/2330966/66538168-945fab00-eb66-11e9-8618-37a8b6788875.png">

**Comment by elbywan** [comment]
Hi @jakemonton,

`hermes-javascript` is not compatible with node 12 (yet). Goal is to make it compatible when node 12 becomes the LTS (in a few weeks).

In the meantime, you can use the current LTS version which is 10.
