### ISSUE TITLE
publish_start_session_notification() not working anymore with latest version of SNIPS

### ISSUE THREAD

**Issue by iotlabo** [snipsco/hermes-protocol#64]
I used the template function to play a TTS message:
hermes.publish_start_session_notification(intent_message.site_id, "My Message", "")
With the old version of python-hermes and SNIPS everything worked. Now nothing happen

**Comment by whitedryas** [comment]
I have checked the publish_start_session_notification function and it seems that the 4th parameter  (e.g 'text') is passed to the SessionInitNotification rather than the 2nd  (session_init_value) . By passing the text as the 4th parameter , it worked for me.

**Comment by anthonyray** [comment]
Hello, this issue was fixed in version `0.3.3` of `hermes-python`.
