### ISSUE TITLE
[Python] Enhancement to manage all the slots in order they were said

### ISSUE THREAD

**Issue by napnap75** [snipsco/hermes-protocol#71]
Hello,

I have developped my own skill to manage my shopping list with Snips.

In this skill, I have two kind of slots:
- items (for example tomatoes)
- optional quantities (for example when I want 4 tomatoes)

In this skill, I can ask to add more than one item in the same intent (for example to add tomatoes and bananas in the same phrase).

With the current implementation of Hermes in Python, when I add two items in one intent, I'm not able to make sure which quantity is for which item.

For example, if I ask to add "tomatoes and 4 bananas", I will get item[0] = "Tomatoes", item[1] = "Bananas" and quantity[0] = 4. But, I would get the exact same result if I asked to add "4 tomatoes and bananas".

Would it be possible to add a new function to get all the slots in a list. In my example, I would get slots[0] = "Tomatoes", slots[1] = 4 and slots[2] = "Bananas" ?

Thanks a lot,

**Comment by anthonyray** [comment]
Hello @napnap75 ! 

Thanks for your suggestion, this could come in handy when manipulating slots, and I may provide an API to perform these kind of operations in the next release of `hermes-python`. 

**However**, the `Slot` class (in `hermes_python.ontology.dialogue.slot` in `0.4.0` of `hermes-python`) has a `range_start` field that gives you the index of the slot in your utterance string. You could use this information as a proxy to sort your slots in the order they are pronounced in your utterance. 

For instance, you could retrieve all the slots in a single lists : 
```python 
slots = [slot_value for slot, slot_value_list in slots.items() for slot_value in slot_value_list ]
```
And then sort them with this field 
```python
sorted(slots, key=lambda slot: slot.range_start)
```

Let me know if that works for you.
