### ISSUE TITLE
[python] Missing __version__ attributes to easily check wrapper version.

### ISSUE THREAD

**Issue by cpoisson** [snipsco/hermes-protocol#81]
**What's missing**

There is no convenience function to retrieve the version of the package. 
One must use pip freeze or `python -c "import pkg_resources; print(pkg_resources.get_distribution('hermes_python').version)"` to retrieve the running version of hermes_python package.

**Use cases**

* debug, support
* application wrapper handling different version of hermes-python in case of breaking changes.

**Envisioned Solution**
The pythonic way to do it --> `hermes_python.__version__`

**Comment by anthonyray** [comment]
Sure, this will be added in `0.4.2`.
