### ISSUE TITLE
[python] Add a methods to activate / deactivate the dialogue sounds feedbacks

### ISSUE THREAD

**Issue by cpoisson** [snipsco/hermes-protocol#83]
**What's the issue**
There is no programmatic way using hermes python to deactivate / activate the sounds feedbacks

The current solution is to use MQTT and thus PAHO

**Use cases targeted**
- "Hey snips, activate / deactivate the sounds feedbacks please"
- Apps could deactivate the sound feedbacks if needed depending on the experience targeted.

**Comment by koenvervloesem** [comment]
To add to this: it would also be interesting to have a way to request the current configuration of the feedback sounds (on or off). So an app could deactivate the feedback sounds temporarily and then reactivate it afterwards, but only if the feedback sounds were already activated. This is a similar situation as https://github.com/snipsco/hermes-protocol/issues/78.

**Comment by fredszaq** [comment]
We may migrate the current feedback toogle on/off routes to the dialogue configure API as this is effectively managed by the dialogue...

**Comment by anthonyray** [comment]
This will be included in the next release of `hermes-python`.
